app/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^job/listing/', show_jobs, name='job-listing'),
    url(r'^student/list/', show_student, name='student-list'),
    url(r'^job/forum/(?P<id>\d)/$', show_job_forum, name='job-forum'),
    url(r'^job/forum/(?P<id>\d)/post/$', add_comment, name='post-comment'),
    url(r'^job/comment/delete/(?P<id>\d)/$', delete_comment, name='delete-comment'),
	url(r'^student/profile/(?P<pk>.*)/$', show_student_profile, name='student-profile'),
    url(r'^company/logout/', auth_logout, name='company-logout'),
    url(r'^job/forum/(?P<id>\d)/apply/$', add_application, name='apply-job'),
]

app_company/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', show_profile, name='profile'),
    url(r'^id/(?P<key>.*)/$', show_profile_by_id, name='profile-by-id'),
    url(r'^job/add/$', add_job, name='company-add-job'),
    url(r'^job/delete/(?P<id>\d)/$', delete_job, name='company-delete-job'),
]

app_mahasiswa/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

ppw_final/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('app_auth.urls', namespace='auth')),
    url(r'^company/', include('app_company.urls', namespace='company')),
    url(r'^mahasiswa/', include('app_mahasiswa.urls', namespace='mahasiswa')),
    url(r'^test/', include('app_render.urls', namespace='render')),
    url(r'^app/', include('app.urls', namespace='app')),
    url(r'^$', RedirectView.as_view(url='auth/', permanent = True), name = '$'),
]

templates/partials/footer.html
<div id="footer">
    <br>
    <br>
    <div class="container">
        <div class="copyright">
            LinkedIn © <span id="copyright-year">2017</span>.
            <!-- {%FOOTER_LINK} -->
        </div>
        <div class="social">
        </div>
    </div>
    <br>
    <br>
</div>

templates/partials/header-company.html
<nav class="navbar">
    <div class="navbar-header">
        <span style="float: left;"><a class="navbar-brand" href="/auth"><img src="../../../static/images_auth/linkedin-logo.png" height="30"></a></span>
    </div>
    <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav">
			<li style="float: right;"><a href="{% url 'auth:company-logout'%}" class="btn nav-btn" onclick="return confirm('Keluar?')"" id="button-logout"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;Logout</a></li>
			<li style="float: right;"><a href="{% url 'company:profile' %}" class="btn nav-btn"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Home</a></li>
		</ul>
	</div>
</nav>

templates/partials/header-user.html
<nav class="navbar">
    <div class="navbar-header">
        <span style="float: left;"><a class="navbar-brand" href="/auth"><img src="../../../static/images_auth/linkedin-logo.png" height="30"></a></span>
    </div>
    <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav">
			<li style="float: right;"><a href="{% url 'auth:company-logout'%}" class="btn nav-btn" onclick="return confirm('Keluar?')"" id="button-logout"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;Logout</a></li>
			<li style="float: right;"><a href="{% url 'mahasiswa:index' %}" class="btn nav-btn"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Home</a></li>
		</ul>
	</div>
</nav>

templates/partials/header.html
<nav class="navbar">
    <div class="navbar-header">
        <span style="float: left;"><a class="navbar-brand" href="/auth"><img src="../../../static/images_auth/linkedin-logo.png" height="30"></a></span>
    </div>
</nav>